defaults:
  - model: chai_model
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_val
  - evaluator: chai_evaluator
  # - score_evaluators@evaluator: bc_iql_eval
  # - score_evaluators@evaluator: iql_eval
  - _self_

train_dataset:
  cache_id: d_train
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/train_rank_reward_cache1.json
    # reward_cache: data/vis_dialogue/processed/visdial_0.5/train_reward_cache2.json
    # additional_scenes: data/vis_dialogue/processed/visdial_0.5/is_it_sunny_events.pkl
    # reward_shift: 30.0
    # reward_scale: 1e6
    mode: env_stops
    # mode: 10_stop
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard
  # token_reward:
  #   name: specified_token_reward
  #   token_file: data/wikitext/wikitext-103-train_gpt2_token_freq.json
  #   scale: 20.0
  #   shift: -1.0
  # top_p: 0.1

eval_dataset:
  cache_id: d_eval
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/val_rank_reward_cache1.json
    # reward_cache: data/vis_dialogue/processed/visdial_0.5/train_reward_cache2.json
    # reward_shift: 30.0
    # reward_scale: 1e6
    mode: env_stops
    # mode: 10_stop
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard
  # token_reward:
  #   name: specified_token_reward
  #   token_file: data/wikitext/wikitext-103-train_gpt2_token_freq.json
  #   scale: 20.0
  #   shift: -1.0
  # top_p: 0.1

model:
  alpha: 0.005
  gamma: 0.99
  use_cache: true
  cache_path: outputs/visual_dialogue/chai_cache2.pkl
  # cache_path: null
  gpt2:
    lm_head: true
    from_pretrained: true
  dataset:
    name: vis_dial_list_dataset
    cache_id: d_train
  load:
    # checkpoint_path: outputs/visual_dialogue/visdial_bc_iql_test1/model.pkl
    # checkpoint_path: outputs/visual_dialogue/visdial_mc_iql_test1/model_360447.pkl
    # checkpoint_path: outputs/visual_dialogue/visdial_iql_standard_new_extraction_test1/model_393215.pkl
    checkpoint_path: outputs/visual_dialogue/visdial_bc_official_test1/model_utterance_converted.pkl
    # checkpoint_path: outputs/visual_dialogue/visdial_hard_yn_iql_official_test2/awac_model.pkl
    strict_load: false

# evaluator:
#   env:
#     url: http://localhost:5001/step_rank
#     dataset:
#       name: vis_dial_list_dataset
#       cache_id: d_eval
#     # reward_shift: 30.0
#     # reward_scale: 1e6
#   verbose: true
#   kind: sample
#   generation_kwargs:
#     max_generation_len: 40
#     # beam_width: 1
#     # temp: 1.0
#     num_generations: 1
#     # max_generation_len: null 
#     # top_k: null
#     # top_p: null


evaluator:
  env:
    url: http://localhost:5001/step_rank
    actor_stop: false
    dataset:
      name: vis_dial_list_dataset
      cache_id: d_eval
    # reward_shift: 30.0
    # reward_scale: 1e6
    yn_reward: -2.0
    yn_reward_kind: hard
  verbose: true
  cache_save_path: null
  generation_kwargs:
    max_generation_len: 40
    num_generations: 5
    generation_batches: 1
    temp: 1.0
    top_k: null
    top_p: null

train:
  save_checkpoint_dir: outputs/visual_dialogue/visdial_hard_yn_chai_test3_3/
  optim_state_path: null
  epochs: 10000000
  dataloader_workers: 1
  bsize: 4
  grad_accum_steps: 4
  log_every: 256
  eval_every: 1024
  save_every: 32768
  max_checkpoints: 1
  eval_bsize: 16
  eval_batches: 1
  lr: 1e-5
  weight_decay: 0.00
  hard_update_every: null
  max_steps: null
  loss:
    q_loss_weight: 1.0
    v_loss_weight: 0.0
    cql_loss_weight: 10.0
    n_generations: 5
    max_generation_len: null
    temp: 1.0
    top_k: null
    top_p: null
    sample_bsize: 4

wandb:
  use_wandb: true
  wandb_project: visdial_iql
